"""Alpha closure type vocabulary — source semantics, not Blender modes."""

from __future__ import annotations

from enum import Enum


class SourceVisibilitySemantic(str, Enum):
    PROVEN_NO_ALPHA_SEMANTICS = "PROVEN_NO_ALPHA_SEMANTICS"
    PROVEN_OPAQUE = "PROVEN_OPAQUE"
    PROVEN_MASKED_VISIBILITY = "PROVEN_MASKED_VISIBILITY"
    PROVEN_BLENDED_VISIBILITY = "PROVEN_BLENDED_VISIBILITY"
    PROVEN_TRANSMISSIVE_VISIBILITY = "PROVEN_TRANSMISSIVE_VISIBILITY"
    PROVEN_SHADING_ONLY_MASK = "PROVEN_SHADING_ONLY_MASK"
    PROVEN_OUTPUT_ALPHA_ONLY = "PROVEN_OUTPUT_ALPHA_ONLY"
    REJECTED_UNSUPPORTED_BRANCH = "REJECTED_UNSUPPORTED_BRANCH"
    UNRESOLVED = "UNRESOLVED"
    # Compatibility aliases (foundation-era names).
    GAME_FILES_PROVEN_OPAQUE = "PROVEN_OPAQUE"
    GAME_FILES_PROVEN_TEXTURE_VISIBILITY_MASK = "PROVEN_MASKED_VISIBILITY"
    GAME_FILES_PROVEN_CUTOUT = "PROVEN_MASKED_VISIBILITY"
    GAME_FILES_PROVEN_SHADING_MASK = "PROVEN_SHADING_ONLY_MASK"
    UNRESOLVED_GAME_FILE_ALPHA = "UNRESOLVED"
    REJECTED_ALPHA_BRANCH = "REJECTED_UNSUPPORTED_BRANCH"


class ChannelClassification(str, Enum):
    AUTHORED_VISIBILITY_MASK_INPUT = "AUTHORED_VISIBILITY_MASK_INPUT"
    BLENDED_OPACITY_INPUT = "BLENDED_OPACITY_INPUT"
    SHADING_ATTENUATION = "SHADING_ATTENUATION"
    TINT_ALPHA = "TINT_ALPHA"
    DETAIL_BLEND_FACTOR = "DETAIL_BLEND_FACTOR"
    NORMAL_BLEND_FACTOR = "NORMAL_BLEND_FACTOR"
    ROUGHNESS_OR_OTHER_PACKED_DATA = "ROUGHNESS_OR_OTHER_PACKED_DATA"
    OUTPUT_ALPHA_INPUT = "OUTPUT_ALPHA_INPUT"
    DUPLICATE_MASK = "DUPLICATE_MASK"
    UNUSED_AFTER_OPTIMISATION = "UNUSED_AFTER_OPTIMISATION"
    UNRESOLVED = "UNRESOLVED"


class ContractShaStatus(str, Enum):
    NO_ALPHA_CONTRACT_REQUIRED = "NO_ALPHA_CONTRACT_REQUIRED"
    CONTRACT_PROVEN = "CONTRACT_PROVEN"
    CONTRACT_PARTIAL = "CONTRACT_PARTIAL"
    CONTRACT_BLOCKED = "CONTRACT_BLOCKED"
    FAMILY_OUTSIDE_PRODUCTION_SCOPE = "FAMILY_OUTSIDE_PRODUCTION_SCOPE"


class BlenderRenderMode(str, Enum):
    OPAQUE = "OPAQUE"
    CLIP = "CLIP"
    HASHED = "HASHED"
    BLEND = "BLEND"
    TRANSMISSION = "TRANSMISSION"


class ThresholdStatus(str, Enum):
    EXACT = "EXACT"
    SOURCE_PASS_DERIVED = "SOURCE_PASS_DERIVED"
    BACKEND_APPROXIMATION = "BACKEND_APPROXIMATION"
    UNUSED = "UNUSED"


class AlphaTransparencyProvenance(str, Enum):
    MATI_EXPLICIT = "MATI_EXPLICIT"
    MATERIAL_TEMPLATE_INHERITED = "MATERIAL_TEMPLATE_INHERITED"
    SHADER_DEFAULT = "SHADER_DEFAULT"
    UNRESOLVED = "UNRESOLVED"


SCHEMA_VERSION = 1
CAR_STANDARD_SHADERBIN_SHA256 = (
    "8df4836b0bf017fccbaf4f5bd5ce7a217f260924e457c72751a2d5df8163df16"
)
ALPHA_TRANSPARENCY_NAMEHASH = 0x5D3E6F2D
ALPHA_TXMP_NAMEHASH = 0x698CA64F
BASECOLORALPHA_TXMP_NAMEHASH = 0x85E937A9
AUTHORED_MASK_EQUATION = "saturate(Alpha.r * BaseColorAlpha.a)"
