"""MojoConfig.xml — Autovista mechanism catalog (FH6).

Generated by MojoConfigGenerator. Lists which Autovista panels/events a car
exposes (``doorLF``, ``wing``, …). Does **not** encode open axis or amp —
those stay in ``.clipd``. Used to filter which clipd hinges we bake.
"""

from __future__ import annotations

import glob
import os
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field


# MojoConfig ``AutovistaEvent Name`` → substrings that appear in clipd
# ``AudioEvent:/Master/Cars/Autovista/AV_*`` paths (case-insensitive).
# Built from fleet MojoConfig × clipd co-occurrence; keep car-agnostic.
# Fleet AV_* leaves (FH6 cars/*.clipd) → MojoConfig AutovistaEvent names.
# Keep tokens specific enough that LIGHTSUP does not match every event.
_EVENT_CLIP_TOKENS: dict[str, tuple[str, ...]] = {
    "doorlf": (
        "DOOROPEN_L",
        "DOORCLOSE_L",
        "SLIDINGDOOROPEN_L",
        "SLIDINGDOORCLOSE_L",
    ),
    "doorrf": (
        "DOOROPEN_R",
        "DOORCLOSE_R",
        "SLIDINGDOOROPEN_R",
        "SLIDINGDOORCLOSE_R",
    ),
    "doorlr": ("DOOROPEN_LR", "DOORCLOSE_LR", "DOOROPEN_RL", "DOORCLOSE_RL"),
    "doorrr": ("DOOROPEN_RR", "DOORCLOSE_RR"),
    "hood": ("HOODOPEN", "HOODCLOSE"),
    "trunk": ("TRUNKOPEN", "TRUNKCLOSE", "TRUNKUP", "TRUNKDOWN"),
    "wing": ("AEROUP", "AERODOWN"),
    "wingf": ("AEROUP", "AERODOWN", "PANELSUP", "PANELSDOWN"),
    "active_aero": ("AEROUP", "AERODOWN"),
    "roof": (
        "ROOFATTACH",
        "ROOFREMOVE",
        "ROOFOPEN",
        "ROOFCLOSE",
        "TOPUP",
        "TOPHIDE",
        "TOPRETURN",
        "TOPCLOSE",
        "WINDOWSUP",
        "WINDOWSDOWN",
    ),
    # Pop-up lights share LIGHTSUP/LIGHTSDOWN for L+R in clipd.
    "headlightl": ("LIGHTSUP", "LIGHTSDOWN", "HEADLIGHT"),
    "headlightr": ("LIGHTSUP", "LIGHTSDOWN", "HEADLIGHT"),
    "storage": ("STORAGEOPEN", "STORAGECLOSE"),
    "storagel": ("STORAGEOPEN", "STORAGECLOSE"),
    "storager": ("STORAGEOPEN", "STORAGECLOSE"),
    "storagem": ("STORAGEOPEN", "STORAGECLOSE"),
    "vent": ("VENTOPEN", "VENTCLOSE"),
}


@dataclass
class MojoConfig:
    """Parsed ``MojoConfig.xml`` for one car."""

    path: str = ""
    # Canonical short names as authored (doorLF, wing, …)
    autovista_events: list[str] = field(default_factory=list)
    # TriggeredDynamics Type attrs
    triggered_dynamics: list[str] = field(default_factory=list)
    # Name → float value
    variable_overrides: dict[str, float] = field(default_factory=dict)
    custom_params: dict[str, float] = field(default_factory=dict)

    @property
    def event_keys(self) -> set[str]:
        return {e.lower() for e in self.autovista_events}


def discover_mojo_config(car_root: str) -> str | None:
    """Find ``MojoConfig.xml`` under the car's Mojo folder."""
    patterns = (
        os.path.join(car_root, "**", "animations", "Mojo", "MojoConfig.xml"),
        os.path.join(car_root, "**", "Animations", "Mojo", "MojoConfig.xml"),
        os.path.join(car_root, "**", "MojoConfig.xml"),
    )
    hits: list[str] = []
    for pat in patterns:
        hits.extend(glob.glob(pat, recursive=True))
    if not hits:
        return None
    # Prefer Scene/animations/Mojo/MojoConfig.xml
    for p in hits:
        norm = p.replace("\\", "/").lower()
        if "/animations/mojo/mojoconfig.xml" in norm:
            return p
    return hits[0]


def parse_mojo_config(path: str) -> MojoConfig:
    """Parse MojoConfigGenerator XML."""
    cfg = MojoConfig(path=path)
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        # Fallback: regex if XML is slightly broken
        text = open(path, encoding="utf-8", errors="replace").read()
        cfg.autovista_events = re.findall(
            r'<AutovistaEvent\s+Name="([^"]+)"', text
        )
        return cfg

    for el in root.iter("AutovistaEvent"):
        name = (el.get("Name") or "").strip()
        if name:
            cfg.autovista_events.append(name)

    for el in root.iter("TriggeredDynamicsDef"):
        t = (el.get("Type") or "").strip()
        if t:
            cfg.triggered_dynamics.append(t)

    for el in root.iter("VariableOverride"):
        name = (el.get("Name") or "").strip()
        if not name:
            continue
        try:
            cfg.variable_overrides[name] = float(el.get("Value") or 0.0)
        except ValueError:
            pass

    for el in root.iter("CustomParam"):
        name = (el.get("Name") or "").strip()
        if not name:
            continue
        try:
            cfg.custom_params[name] = float(el.get("Value") or 0.0)
        except ValueError:
            pass

    return cfg


def load_mojo_config(car_root: str) -> MojoConfig | None:
    path = discover_mojo_config(car_root)
    if not path:
        return None
    return parse_mojo_config(path)


def clip_event_matches_config(event_path: str, config: MojoConfig | None) -> bool:
    """True if ``event_path`` belongs to a declared AutovistaEvent (or no config).

    When MojoConfig is missing, keep all clipd events (legacy / incomplete extract).
    When present with an empty AutovistaEvents list, keep none of the panel opens
    (open-cockpit / no-door cars still may have zero events).
    """
    if config is None:
        return True
    if not config.autovista_events:
        # Explicit empty catalog — only keep non-panel util clips if any.
        # In practice these cars have no door/hood clips either.
        return False

    upper = (event_path or "").upper()
    # Strip to the AV_* leaf for matching.
    leaf = upper.rsplit("/", 1)[-1]
    if leaf.startswith("AV_"):
        leaf = leaf[3:]

    for key in config.event_keys:
        tokens = _EVENT_CLIP_TOKENS.get(key)
        if tokens is None:
            # Unknown mechanism name: match if the name itself appears in the path.
            if key.upper() in upper or key.upper().replace("_", "") in leaf.replace("_", ""):
                return True
            continue
        for tok in tokens:
            if tok.upper() in leaf or tok.upper() in upper:
                return True
    return False


def filter_hinges_by_mojo_config(hinges, config: MojoConfig | None):
    """Drop hinge channels whose AudioEvent is outside MojoConfig AutovistaEvents."""
    if config is None:
        return list(hinges)
    return [h for h in hinges if clip_event_matches_config(getattr(h, "event", "") or "", config)]
